import time
from ddgs import DDGS

def search_duckduckgo(query: str, max_results: int = 4, max_retries: int = 2) -> str:
    """
    Executes live search using the exact search query generated by the LLM.
    No hardcoded keywords or string tampering.
    """
    for attempt in range(max_retries + 1):
        try:
            with DDGS(timeout=7) as ddgs:
                results = list(ddgs.text(query, max_results=max_results))
                if not results:
                    return ""

                snippets = []
                for i, r in enumerate(results, 1):
                    title = r.get('title', '').strip()
                    body = r.get('body', '').strip()
                    if body:
                        snippets.append(f"[{i}] {title}: {body}")
                return "\n\n".join(snippets)
                
        except Exception as e:
            if attempt < max_retries:
                time.sleep(1.5 * (attempt + 1))
            else:
                print(f"⚠️ Search error: {e}")
                return ""
    return ""